export const roomsData = [
  {
    id: 1,
    name: "Standard Room",
    price: 1050,
    bed_type: "Double",
    max_occupancy: 2,
    amenities: ["TV", "Wifi", "Air Conditioning"],
    city: "Bangalore",
  },
  {
    id: 2,
    name: "Deluxe Room",
    price: 1200,
    bed_type: "King",
    max_occupancy: 2,
    amenities: ["TV", "Wifi", "Air Conditioning", "Mini Bar"],
    city: "Mumbai",
  },
  {
    id: 3,
    name: "Suite",
    price: 1350,
    bed_type: "King",
    max_occupancy: 4,
    amenities: ["TV", "Wifi", "Air Conditioning", "Mini Bar", "Kitchenette"],
    city: "Hyderabad",
  },
  {
    id: 4,
    name: "Executive Room",
    price: 1425,
    bed_type: "Double",
    max_occupancy: 2,
    amenities: ["TV", "Wifi", "Air Conditioning"],
    city: "Kolkata",
  },
  {
    id: 5,
    name: "Luxury Suite",
    price: 1249,
    bed_type: "King",
    max_occupancy: 4,
    amenities: ["TV", "Wifi", "Air Conditioning", "Mini Bar", "Kitchenette"],
    city: "Delhi",
  },
  {
    id: 6,
    name: "Standard Room",
    price: 1100,
    bed_type: "Double",
    max_occupancy: 2,
    amenities: ["TV", "Wifi", "Air Conditioning"],
    city: "Chennai",
  },
  {
    id: 7,
    name: "Deluxe Room",
    price: 1150,
    bed_type: "King",
    max_occupancy: 2,
    amenities: ["TV", "Wifi", "Air Conditioning", "Mini Bar"],
    city: "Jaipur",
  },
  {
    id: 8,
    name: "Suite",
    price: 1250,
    bed_type: "King",
    max_occupancy: 4,
    amenities: ["TV", "Wifi", "Air Conditioning", "Mini Bar", "Kitchenette"],
    city: "Goa",
  },
  {
    id: 9,
    name: "Executive Room",
    price: 1300,
    bed_type: "Double",
    max_occupancy: 2,
    amenities: ["TV", "Wifi", "Air Conditioning"],
    city: "Agra",
  },
  {
    id: 10,
    name: "Luxury Suite",
    price: 1450,
    bed_type: "King",
    max_occupancy: 4,
    amenities: ["TV", "Wifi", "Air Conditioning", "Mini Bar", "Kitchenette"],
    city: "Pune",
  },

  {
    id: 11,
    name: "Standard Room",
    price: 1300,
    bed_type: "Double",
    max_occupancy: 2,
    amenities: ["TV", "Wifi", "Air Conditioning"],
    city: "Bengaluru",
  },
  {
    id: 12,
    name: "Deluxe Room",
    price: 1250,
    bed_type: "King",
    max_occupancy: 2,
    amenities: ["TV", "Wifi", "Air Conditioning", "Mini Bar"],
    city: "Mumbai",
  },
  {
    id: 13,
    name: "Suite",
    price: 1200,
    bed_type: "King",
    max_occupancy: 4,
    amenities: ["TV", "Wifi", "Air Conditioning", "Mini Bar", "Kitchenette"],
    city: "Hyderabad",
  },
  {
    id: 14,
    name: "Executive Room",
    price: 1400,
    bed_type: "Double",
    max_occupancy: 2,
    amenities: ["TV", "Wifi", "Air Conditioning"],
    city: "Kolkata",
  },
  {
    id: 15,
    name: "Luxury Suite",
    price: 1100,
    bed_type: "King",
    max_occupancy: 4,
    amenities: ["TV", "Wifi", "Air Conditioning", "Mini Bar", "Kitchenette"],
    city: "Delhi",
  },
  {
    id: 16,
    name: "Standard Room",
    price: 1050,
    bed_type: "Double",
    max_occupancy: 2,
    amenities: ["TV", "Wifi", "Air Conditioning"],
    city: "Chennai",
  },
  {
    id: 17,
    name: "Deluxe Room",
    price: 1350,
    bed_type: "King",
    max_occupancy: 2,
    amenities: ["TV", "Wifi", "Air Conditioning", "Mini Bar"],
    city: "Jaipur",
  },
  {
    id: 18,
    name: "Suite",
    price: 1250,
    bed_type: "King",
    max_occupancy: 4,
    amenities: ["TV", "Wifi", "Air Conditioning", "Mini Bar", "Kitchenette"],
    city: "Goa",
  },
  {
    id: 19,
    name: "Executive Room",
    price: 1150,
    bed_type: "Double",
    max_occupancy: 2,
    amenities: ["TV", "Wifi", "Air Conditioning"],
    city: "Agra",
  },
  {
    id: 20,
    name: "Luxury Suite",
    price: 1450,
    bed_type: "King",
    max_occupancy: 4,
    amenities: ["TV", "Wifi", "Air Conditioning", "Mini Bar", "Kitchenette"],
    city: "Pune",
  },
];

export const cities = [
  {
    id: 0,
    name: "All",
  },
  {
    id: 1,
    name: "Bangalore",
  },
  {
    id: 2,
    name: "Mumbai",
  },
  {
    id: 3,
    name: "Hyderabad",
  },
  {
    id: 4,
    name: "Kolkata",
  },
  {
    id: 5,
    name: "Delhi",
  },
  {
    id: 6,
    name: "Chennai",
  },
  {
    id: 7,
    name: "Jaipur",
  },
  {
    id: 8,
    name: "Goa",
  },
  {
    id: 9,
    name: "Agra",
  },
  {
    id: 10,
    name: "Pune",
  },
];
